spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://ec2-3-35-137-161.ap-northeast-2.compute.amazonaws.com:3306/spring_market?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: spring_market
      password: spring1234

